### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('class="schedule-map-left"') is not a valid name.

### ISSUE THREAD

**Issue by phammer** [mattberkowitz/autoclose-html#35]
Uncaught InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('class="schedule-map-left"') is not a valid name.

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [autoclose-html](https://github.com/mattberkowitz/autoclose-html) package, v0.12.0
### Steps To Reproduce
1. Open some HTML file
2. type `<class="bla"` (which is obviously wrong because of the missing element name, e.g., `div`.)
3. type `>` to close the element => Exception is thrown

I understand that the written HTML is not valid, but Atom shouldn't throw an exception because of that. An alert that I wrote completely wrong code would be fine however. 
### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:121

Error: Failed to execute 'createElement' on 'Document': The tag name provided ('class="schedule-map-left"') is not a valid name.
  at Error (native)
  at Object.module.exports.isInline (/Users/ph/.atom/packages/autoclose-html/lib/autoclose-html.coffee:53:24)
  at Object.module.exports.execAutoclose (/Users/ph/.atom/packages/autoclose-html/lib/autoclose-html.coffee:89:25)
  at /Users/ph/.atom/packages/autoclose-html/lib/autoclose-html.coffee:106:18
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:591:12)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:503:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:446:43)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:738:31
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:777:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1146:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:770:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:735:21)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:73:27)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:653:23
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1146:26)
  at [object Object].module.exports.React.createClass.onTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:652:30)
  at HTMLDivElement.boundMethod (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)

```

/cc @atom/core

**Comment by fhernandez204** [comment]
I have this problem
