### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

### ISSUE THREAD

**Issue by pTran24** [mattberkowitz/autoclose-html#50]
[Enter steps to reproduce below:]

1. I'm working with a .js file and this error occurs as soon as I complete the a <div> tag and it auto-completes the closing tag for me. The closing tag is created but then the error shortly follows. Early today I had an issue with the bracket-matching package throwing a similar error, so I installed this package.

packages installed: vim-mode, sublime-style-column-selection, autoclose.html

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [autoclose-html](https://github.com/mattberkowitz/autoclose-html) package, v0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:503

TypeError: Cannot read property 'tokenAtBufferColumn' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenForPosition (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:503:38)
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:496:22)
  at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1044:35)
  at TextEditor.module.exports.TextEditor.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2413:33)
  at LanguageMode.module.exports.LanguageMode.suggestedIndentForBufferRow (/Applications/Atom.app/Contents/Resources/app/src/language-mode.js:315:37)
  at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/language-mode.js:374:26)
  at TextEditor._results.push._this.(anonymous function) [as autoIndentBufferRow] (/Applications/Atom.app/Contents/Resources/app/node_modules/delegato/lib/delegator.js:67:61)
  at /Users/xajin/.atom/packages/autoclose-html/lib/autoclose-html.coffee:98:28

```

### Commands

```
     -0:26.1 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:25.2 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:23.4 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:20.6 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:18.8 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:16.9 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:16.5 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:12.8 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:11.9 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:11.0 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:11.0 snippets:expand (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:11.0 editor:indent (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:10.7 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:10.7 snippets:expand (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:10.7 editor:indent (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:09.9 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "bracket-matcher"
    ]
  },
  "autoclose-html": {
    "forceInline": "p, h1, h2, h3"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.21.2
autoclose-html, v0.14.0
compare-files, v0.3.1
vim-mode, v0.30.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by mattberkowitz** [comment]
Hey, I'm not able to reproduce this error. I'll keep playing around with it, let me know if you come up with any additional information

**Comment by pTran24** [comment]
Hey, thanks for looking into this. I updated to to OS X Yosemite 10.10.2 this morning and the problem seems to go away. I’ll let you know if I run into this again.
