### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by INALOW** [mattberkowitz/autoclose-html#55]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autoclose-html](https://github.com/mattberkowitz/autoclose-html) package, v0.15.0

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/INALOW/.atom/packages/autoclose-html/lib/autoclose-html.coffee:108

TypeError: Cannot read property 'name' of undefined
  at /Users/INALOW/.atom/packages/autoclose-html/lib/autoclose-html.coffee:108:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.handleGrammarChange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2736:27)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:196:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:164:27)
  at DisplayBuffer.module.exports.DisplayBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1042:35)
  at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2357:33)
  at GrammarListView.module.exports.GrammarListView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/grammar-selector/lib/grammar-list-view.js:60:21)
  at GrammarListView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at HTMLLIElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -0:00.0 grammar-selector:show (atom-text-editor.editor.editor-colors)
```

### Config

```
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "autoclose-html": {}
}
```

### Installed Packages

```coffee
# User
Stylus, v0.5.3
autoclose-html, v0.15.0
color-picker, v1.4.4
emmet, v2.3.3
language-stylus, v0.1.0
language-swift, v0.3.0
processing-language, v0.1.0
project-manager, v1.15.5
script, v2.16.0
seti-syntax, v0.2.1
seti-ui, v0.6.3
tag, v0.2.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by mattberkowitz** [comment]
You're quite a few versions behind on atom. Can you try updating that first and see if it clears things up?
