### ISSUE TITLE
Failed to activate the autoclose-html package

### ISSUE THREAD

**Issue by CarlT1989** [mattberkowitz/autoclose-html#60]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [autoclose-html](https://github.com/mattberkowitz/autoclose-html) package, v0.15.0

### Stack Trace

Failed to activate the autoclose-html package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at /Users/carl.taylor/.atom/packages/autoclose-html/lib/autoclose-html.coffee:40:42
    at Config.module.exports.Config.observeKeyPath (/Users/carl.taylor/Downloads/Atom.app/Contents/Resources/app/src/config.js:544:7)
    at Config.module.exports.Config.observe (/Users/carl.taylor/Downloads/Atom.app/Contents/Resources/app/src/config.js:126:21)
    at Object.module.exports.activate (/Users/carl.taylor/.atom/packages/autoclose-html/lib/autoclose-html.coffee:38:19)
    at Package.module.exports.Package.activateNow (/Users/carl.taylor/Downloads/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /Users/carl.taylor/Downloads/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/Users/carl.taylor/Downloads/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/Users/carl.taylor/Downloads/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/carl.taylor/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /Users/carl.taylor/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "monokai"
    ],
    "disabledPackages": [
      "autocomplete-snippets",
      "git-plus"
    ]
  },
  "autoclose-html": {}
}
```

### Installed Packages

```coffee
# User
atom-bootstrap3, v1.2.0
atom-color-highlight, v3.0.8
autoclose-html, v0.15.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.8.0
autoprefixer, v2.2.1
emmet, v2.3.6
file-icons, v1.5.3
highlight-line, v0.10.1
isotope-ui, v2.0.1
javascript-snippets, v1.0.0
minimap, v4.7.5
monokai, v0.13.0

# Dev
No dev packages
```

**Comment by sh4nks** [comment]
Just ran into the same error. I updated atom from 0.189 to 0.190

**Comment by mattberkowitz** [comment]
I'll try and take a look this weekend, I haven't updated yet myself

**Comment by sh4nks** [comment]
The strange thing is, the error only popped up on the first run after the upgrade - now it seems to be good again (at least for me)

**Comment by brandom** [comment]
Got this error right after upgrading to 0.191 as well. No error on subsequent starts. Similar behavior from richtmat/lodash-snippets#7
